// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type PostApiOptionGameQueryRealTimePriceData = {
    body?: {
        /**
         * 股票代码
         */
        stock: string;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/game/queryRealTimePrice';
};

export type PostApiOptionGameQueryRealTimePriceResponses = {
    200: {
        code: number;
        message: string;
        data: {
            priceNow: number;
        };
    };
};

export type PostApiOptionGameQueryRealTimePriceResponse = PostApiOptionGameQueryRealTimePriceResponses[keyof PostApiOptionGameQueryRealTimePriceResponses];

export type PostApiOptionGameFetchUsStockKLineData = {
    body?: {
        /**
         * 股票代码
         */
        stock: string;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/game/fetchUSStockKLine';
};

export type PostApiOptionGameFetchUsStockKLineResponses = {
    200: {
        code: number;
        message: string;
        data: {
            dayKLines: Array<{
                id: number;
                stock: string;
                open: number;
                close: number;
                high: number;
                low: number;
                date: string;
                volume: number;
                changeVolumeRate: number;
                pe: number;
            }>;
        };
    };
};

export type PostApiOptionGameFetchUsStockKLineResponse = PostApiOptionGameFetchUsStockKLineResponses[keyof PostApiOptionGameFetchUsStockKLineResponses];

export type PostApiOptionGameFetchUsOptionChainData = {
    body?: {
        /**
         * 股票代码
         */
        stock: string;
        /**
         * 查询月份数
         */
        howManyMonths: number;
        /**
         * 是否为call
         */
        call: boolean;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/game/fetchUSOptionChain';
};

export type PostApiOptionGameFetchUsOptionChainResponses = {
    200: {
        code: number;
        message: string;
        data: {
            optionDataSet: Array<{
                stock: string;
                optionCode: string;
                strikePrice: number;
                type: string;
                askPrice: number;
                bidPrice: number;
                contractSize: number;
                strikeTime: string;
            }>;
        };
    };
};

export type PostApiOptionGameFetchUsOptionChainResponse = PostApiOptionGameFetchUsOptionChainResponses[keyof PostApiOptionGameFetchUsOptionChainResponses];

export type PostApiOptionGameListStockBuyCallPercentAdvData = {
    body?: {
        /**
         * 股票代码
         */
        stock: string;
        /**
         * 股票涨幅
         */
        percent: number;
        /**
         * 查询月份数
         */
        howManyMonths: number;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/game/listStockBuyCallPercentAdv';
};

export type PostApiOptionGameListStockBuyCallPercentAdvResponses = {
    200: {
        code: number;
        message: string;
        data: {
            buyCallResults: Array<Array<{
                stock: string;
                StrikeDate: string;
                nowPrice: number;
                planPrice: number;
                probability: number;
                cost: number;
                maxEarn: number;
                roi: number;
                buyDescription: string;
                sellDescription: string;
                power: number;
                balancePrice: number;
                days: number;
                markGood: boolean;
                mark: number;
                weekWaveInExpectProb: number;
                strikeDate: string;
            }>>;
        };
    };
};

export type PostApiOptionGameListStockBuyCallPercentAdvResponse = PostApiOptionGameListStockBuyCallPercentAdvResponses[keyof PostApiOptionGameListStockBuyCallPercentAdvResponses];

export type PostApiOptionGameListStockBuyPutPercentAdvData = {
    body?: {
        /**
         * 股票代码
         */
        stock: string;
        /**
         * 股票涨幅
         */
        percent: number;
        /**
         * 查询月份数
         */
        howManyMonths: number;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/game/listStockBuyPutPercentAdv';
};

export type PostApiOptionGameListStockBuyPutPercentAdvResponses = {
    200: {
        code: number;
        message: string;
        data: {
            buyPutResults: Array<Array<{
                stock: string;
                StrikeDate: string;
                nowPrice: number;
                planPrice: number;
                probability: number;
                cost: number;
                maxEarn: number;
                roi: number;
                buyDescription: string;
                sellDescription: string;
                power: number;
                balancePrice: number;
                days: number;
                markGood: boolean;
                mark: number;
                weekWaveInExpectProb: number;
                strikeDate: string;
            }>>;
        };
    };
};

export type PostApiOptionGameListStockBuyPutPercentAdvResponse = PostApiOptionGameListStockBuyPutPercentAdvResponses[keyof PostApiOptionGameListStockBuyPutPercentAdvResponses];
