// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type PostApiOptionUserThirdPartyLoginData = {
    body?: {
        /**
         * 用户openId
         *
         * 合作方用户对外唯一id
         */
        openId: string;
        /**
         * 昵称
         */
        nickName?: string;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/user/thirdPartyLogin';
};

export type PostApiOptionUserThirdPartyLoginResponses = {
    200: {
        /**
         * 响应码
         *
         * 0-成功
         */
        code: number;
        /**
         * 响应信息
         */
        message: string;
        /**
         * 响应数据
         */
        data: {
            /**
             * 昵称
             */
            nickName?: string;
            /**
             * token
             *
             * 后续充值，提交任务时使用
             */
            token: string;
            /**
             * 过期时间
             *
             * 时间戳，毫秒
             */
            expiredAt: number;
            /**
             * 余额
             *
             * 金币数，单位：分
             */
            balance: number;
            /**
             * 状态
             *
             * 0-待激活 1-已激活
             */
            status: number;
            /**
             * 会员类型
             *
             * Month-包月会员
             * Year-年会员
             */
            vipType?: string;
            /**
             * 会员有效开始时间
             *
             * 时间戳，毫秒
             */
            vipValidFrom?: number;
            /**
             * 会员过期时间
             *
             * 时间戳，毫秒
             */
            vipValidTo?: number;
        };
    };
};

export type PostApiOptionUserThirdPartyLoginResponse = PostApiOptionUserThirdPartyLoginResponses[keyof PostApiOptionUserThirdPartyLoginResponses];

export type PostApiOptionRechargeGetRechargeInfoData = {
    body?: {
        /**
         * 用户token
         */
        token: string;
        /**
         * 充值类型
         *
         * coin-金币充值
         * vip-会员充值
         * 不传返回所有商品
         */
        type?: string;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': string;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/recharge/getRechargeInfo';
};

export type PostApiOptionRechargeGetRechargeInfoResponses = {
    200: {
        /**
         * 响应码
         *
         * 0-成功
         */
        code: number;
        /**
         * 响应消息
         */
        message: string;
        /**
         * 响应数据体
         */
        data: {
            /**
             * 用户余额
             *
             * 金币数
             */
            balance: number;
            /**
             * 充值商品列表
             */
            productList: Array<{
                /**
                 * 商品id
                 */
                id: number;
                /**
                 * 充值金币数
                 *
                 * 金币充值商品有值
                 */
                coinsNum: number;
                /**
                 * 赠送金币数
                 *
                 * 金币充值商品有值
                 */
                giftCoinNum: number;
                /**
                 * 商品价格-美元
                 *
                 * 单位：分
                 */
                usMoney: number;
                /**
                 * 商品价格-人民币
                 *
                 * 单位：分
                 */
                rmbMoney: number;
                /**
                 * 商品价格-港币
                 *
                 * 单位：分
                 */
                hkMoney: number;
                /**
                 * 会员类型
                 *
                 * 会员充值商品有值
                 * Month-包月会员
                 * Season-季度会员
                 * HalfYear-半年会员
                 */
                vipType?: string;
            }>;
        };
    };
};

export type PostApiOptionRechargeGetRechargeInfoResponse = PostApiOptionRechargeGetRechargeInfoResponses[keyof PostApiOptionRechargeGetRechargeInfoResponses];

export type PostApiOptionRechargeThirdPartyOpenVipData = {
    body?: {
        /**
         * 用户token
         */
        token: string;
        /**
         * 订单号，全局唯一，防止重复下单
         */
        orderId: string;
        /**
         * 商品id
         * 102-包月会员
         * 103-季度会员
         * 104-半年度会员
         */
        productId: number;
        /**
         * 支付的币种
         * HKD-港币
         * USD-美元
         * CNY-人名币
         *
         */
        currency: string;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/recharge/thirdPartyOpenVip';
};

export type PostApiOptionRechargeThirdPartyOpenVipResponses = {
    200: {
        /**
         * 响应码
         *
         * 0-成功
         * 4006-订单已存在
         */
        code: number;
        /**
         * 响应信息
         */
        message: string;
        /**
         * 响应数据
         */
        data: {
            /**
             * 昵称
             */
            nickName: string;
            /**
             * 余额
             *
             * 金币数，单位：分
             */
            balance: number;
            /**
             * 状态
             *
             * 0-待激活 1-已激活
             */
            status: number;
            /**
             * 是否充值过
             */
            hasRecharge: boolean;
            /**
             * 会员类型
             *
             * Month-包月会员
             * Year-年会员
             */
            vipType: string;
            /**
             * 会员有效开始时间
             *
             * 时间戳，单位：毫秒
             */
            vipValidFrom: number;
            /**
             * 会员过期时间
             *
             * 时间戳，单位：毫秒
             */
            vipValidTo: number;
            /**
             * 用户注册时间
             *
             * 时间戳，单位：毫秒
             */
            createTime: number;
            /**
             * 用户更新信息
             *
             * 时间戳，单位：毫秒
             */
            updateTime: number;
        };
    };
};

export type PostApiOptionRechargeThirdPartyOpenVipResponse = PostApiOptionRechargeThirdPartyOpenVipResponses[keyof PostApiOptionRechargeThirdPartyOpenVipResponses];

export type PostApiOptionAnalysisCalcRealTimeTaskPriceData = {
    body?: {
        /**
         * 类型
         *
         * 0-Buy Call
         * 1-Sell Call
         * 2-Buy Put
         * 3-Sell Put
         * 4-智能看涨组合
         * 5-智能看跌组合
         */
        type: number;
        /**
         * 股票代码
         */
        stockCodes: Array<string>;
        /**
         * 用户token
         */
        token: string;
        /**
         * 查询天数
         */
        days: number;
        /**
         * 交易市场
         *
         * US-美股
         * HK-港股
         * 默认美股
         */
        marketCode?: string;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/analysis/calcRealTimeTaskPrice';
};

export type PostApiOptionAnalysisCalcRealTimeTaskPriceResponses = {
    200: {
        /**
         * 响应码
         *
         * 0-成功
         */
        code: number;
        /**
         * 响应信息
         */
        message: string;
        /**
         * 响应体
         */
        data: {
            /**
             * 任务价格
             *
             * 金币数，单位：分
             */
            taskPrice: number;
            /**
             * 当月剩余周期性金币数
             *
             * 针对会员场景，每月有3000金币额度
             */
            remainCycleCoins: number;
            /**
             * 扣费来源
             *
             * true-从周期性金币数扣减
             * false-从余额扣减
             */
            deductFromCycleCoins: boolean;
            /**
             * 会员类型
             *
             * Month-包月会员
             * Year-年会员
             */
            vipType?: string;
            /**
             * 会员有效开始时间
             *
             * 时间戳，毫秒
             */
            vipValidFrom?: number;
            /**
             * 会员过期时间
             *
             * 时间戳，毫秒
             */
            vipValidTo?: number;
        };
    };
};

export type PostApiOptionAnalysisCalcRealTimeTaskPriceResponse = PostApiOptionAnalysisCalcRealTimeTaskPriceResponses[keyof PostApiOptionAnalysisCalcRealTimeTaskPriceResponses];

export type PostApiOptionAnalysisAnalyzeTaskRealTimeData = {
    body?: {
        /**
         * 类型
         *
         * 0-Buy Call
         * 1-Sell Call
         * 2-Buy Put
         * 3-Sell Put
         * 4-智能看涨组合
         * 5-智能看跌组合
         */
        type: number;
        /**
         * 股票代码列表
         */
        stockCodes: Array<string>;
        /**
         * 用户token
         */
        token: string;
        /**
         * 查询天数
         */
        days: number;
        /**
         * 交易市场
         *
         * US-美股
         * HK-港股
         * 默认美股
         */
        marketCode?: string;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/analysis/analyzeTaskRealTime';
};

export type PostApiOptionAnalysisAnalyzeTaskRealTimeResponses = {
    200: {
        /**
         * 响应码
         *
         * 0-成功
         * 3002-任务id不存在
         */
        code: number;
        /**
         * 响应信息
         */
        message: string;
        /**
         * 响应数据体
         */
        data: {
            /**
             * 任务信息
             */
            taskInfo: {
                /**
                 * 任务id
                 */
                id: number;
                /**
                 * 任务价格
                 */
                taskPrice: number;
                /**
                 * 任务状态
                 *
                 * 0-已提交，10-计算中，20-计算完成，30-计算失败
                 */
                taskStatus: number;
                /**
                 * 类型
                 *
                 * 0-Buy Call，1-Sell Call，2-Buy Put，3-Sell Put
                 */
                type: number;
                /**
                 * 股票代码
                 */
                stockCodes: Array<string>;
                /**
                 * 开始日期
                 *
                 * 格式：yyyy-MM-dd
                 */
                startDate: string;
                /**
                 * 结束日期
                 *
                 * 格式：yyyy-MM-dd
                 */
                endDate: string;
                /**
                 * 查询天数
                 */
                days: number;
                /**
                 * 等待时间
                 */
                waitingTime: number;
                /**
                 * 任务完成时间
                 */
                taskFinishTime: number;
                /**
                 * 任务创建时间
                 */
                createTime: number;
                /**
                 * 股票市场
                 */
                marketCode: string;
                /**
                 * 是否从会员额度扣费
                 */
                useVip: boolean;
            };
            /**
             * 分析结果列表
             */
            optionList: Array<{
                /**
                 * 任务id
                 */
                taskId: number;
                /**
                 * 剩余周期
                 */
                remainingPeriod: number;
                /**
                 * 股票代码
                 */
                stockCode: string;
                /**
                 * 类型
                 *
                 * Call/Put
                 */
                optionType: string;
                /**
                 * 期权价格
                 */
                strikePrice: number;
                /**
                 * 行权日期
                 */
                strikeTime: string;
                /**
                 * 年化收益率/年化成本率
                 *
                 * 在类型中选卖方Sell时叫‘年化收益率’，选买方Buy时则改为’年化成本率’
                 */
                annualizedRate: number;
                /**
                 * 行权概率
                 */
                exerciseProbability: number;
                /**
                 * 权利金
                 */
                premium: number;
                /**
                 * 溢价
                 *
                 * 期权价格和实际价格的差距百分比
                 */
                diffRate: number;
                /**
                 * 推荐值
                 *
                 * 分数越高越好
                 */
                score: number;
                /**
                 * 期权编码
                 */
                optCode: string;
            }>;
        };
    };
};

export type PostApiOptionAnalysisAnalyzeTaskRealTimeResponse = PostApiOptionAnalysisAnalyzeTaskRealTimeResponses[keyof PostApiOptionAnalysisAnalyzeTaskRealTimeResponses];

export type PostApiOptionAnalysisThirdPartySubmitTaskData = {
    body?: {
        /**
         * 类型
         *
         * 0-Buy Call
         * 1-Sell Call
         * 2-Buy Put
         * 3-Sell Put
         */
        type: number;
        /**
         * 股票代码列表
         */
        stockCodes: Array<string>;
        /**
         * 用户token
         */
        token: string;
        /**
         * 查询天数
         */
        days: number;
        /**
         * 交易市场
         *
         * US-美股
         * HK-港股
         * 默认美股
         */
        marketCode?: string;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/analysis/thirdPartySubmitTask';
};

export type PostApiOptionAnalysisThirdPartySubmitTaskResponses = {
    200: {
        /**
         * 响应码
         *
         * 0-成功
         * 3001-余额不足
         */
        code: number;
        /**
         * 响应信息
         */
        message: string;
        /**
         * 响应体
         */
        data: {
            /**
             * 任务id
             *
             * 后续可以通过任务id查询分析结果
             */
            taskId: number;
        };
    };
};

export type PostApiOptionAnalysisThirdPartySubmitTaskResponse = PostApiOptionAnalysisThirdPartySubmitTaskResponses[keyof PostApiOptionAnalysisThirdPartySubmitTaskResponses];

export type PostApiOptionAnalysisGetTaskResultData = {
    body?: {
        /**
         * 任务id
         *
         * 提交任务时返回的id
         */
        taskId: number;
        /**
         * 用户token
         */
        token: string;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/analysis/getTaskResult';
};

export type PostApiOptionAnalysisGetTaskResultResponses = {
    200: {
        /**
         * 响应码
         *
         * 0-成功
         * 3002-任务id不存在
         */
        code: number;
        /**
         * 响应信息
         */
        message: string;
        /**
         * 响应数据体
         */
        data: {
            /**
             * 任务信息
             */
            taskInfo: {
                /**
                 * 任务id
                 */
                id: number;
                /**
                 * 任务价格
                 */
                taskPrice: number;
                /**
                 * 任务状态
                 *
                 * 0-已提交，10-计算中，20-计算完成，30-计算失败
                 */
                taskStatus: number;
                /**
                 * 类型
                 *
                 * 0-Buy Call，1-Sell Call，2-Buy Put，3-Sell Put
                 */
                type: number;
                /**
                 * 股票代码
                 */
                stockCodes: Array<string>;
                /**
                 * 开始日期
                 *
                 * 格式：yyyy-MM-dd
                 */
                startDate: string;
                /**
                 * 结束日期
                 *
                 * 格式：yyyy-MM-dd
                 */
                endDate: string;
                /**
                 * 查询天数
                 */
                days: number;
                /**
                 * 等待时间
                 */
                waitingTime: number;
                /**
                 * 任务完成时间
                 */
                taskFinishTime: number;
                /**
                 * 任务创建时间
                 */
                createTime: number;
                /**
                 * 股票市场
                 */
                marketCode: string;
                /**
                 * 是否从会员额度扣费
                 */
                useVip: boolean;
            };
            /**
             * 分析结果列表
             */
            optionList: Array<{
                /**
                 * 任务id
                 */
                taskId: number;
                /**
                 * 剩余周期
                 */
                remainingPeriod: number;
                /**
                 * 股票代码
                 */
                stockCode: string;
                /**
                 * 类型
                 *
                 * Call/Put
                 */
                optionType: string;
                /**
                 * 期权价格
                 */
                strikePrice: number;
                /**
                 * 行权日期
                 */
                strikeTime: string;
                /**
                 * 年化收益率/年化成本率
                 *
                 * 在类型中选卖方Sell时叫‘年化收益率’，选买方Buy时则改为’年化成本率’
                 */
                annualizedRate: number;
                /**
                 * 行权概率
                 */
                exerciseProbability: number;
                /**
                 * 权利金
                 */
                premium: number;
                /**
                 * 溢价
                 *
                 * 期权价格和实际价格的差距百分比
                 */
                diffRate: number;
                /**
                 * 推荐值
                 *
                 * 分数越高越好
                 */
                score: number;
            }>;
        };
    };
};

export type PostApiOptionAnalysisGetTaskResultResponse = PostApiOptionAnalysisGetTaskResultResponses[keyof PostApiOptionAnalysisGetTaskResultResponses];

export type PostApiOptionAnalysisGetHistoryTasksData = {
    body?: {
        /**
         * 用户token
         */
        token: string;
        /**
         * 股票市场
         *
         * US-美股
         * HK-港股
         */
        marketCode?: string;
        /**
         * 页码
         *
         * 从1开始，默认1
         */
        page?: number;
        /**
         * 每页记录数
         *
         * 默认200
         */
        pageSize?: number;
    };
    headers: {
        /**
         * 接入方apikey，联系平台提供
         */
        'x-api-key': string;
        /**
         * 请求id，全局唯一，用于防止请求回放和问题定位
         */
        'x-request-id': string;
        /**
         * 请求时间戳,毫秒
         */
        'x-timestamp': number;
        /**
         * 签名，具体规则见全局约定文档
         */
        'x-sign': string;
    };
    path?: never;
    query?: never;
    url: '/api/option/analysis/getHistoryTasks';
};

export type PostApiOptionAnalysisGetHistoryTasksResponses = {
    200: {
        /**
         * 响应码
         *
         * 0-成功
         */
        code: number;
        /**
         * 响应信息
         */
        message: string;
        /**
         * 响应体
         */
        data: {
            /**
             * 历史任务列表
             */
            taskList: Array<{
                /**
                 * 任务id
                 */
                id: number;
                /**
                 * 任务价格
                 */
                taskPrice: number;
                /**
                 * 任务状态
                 *
                 * 0-已提交，10-计算中，20-计算完成，30-计算失败
                 */
                taskStatus: number;
                /**
                 * 类型
                 *
                 * 0-Buy Call，1-Sell Call，2-Buy Put，3-Sell Put
                 */
                type: number;
                /**
                 * 股票代码
                 */
                stockCodes: Array<string>;
                /**
                 * 开始日期
                 */
                startDate: string;
                /**
                 * 结束日期
                 */
                endDate: string;
                /**
                 * 查询天数
                 */
                days: number;
                /**
                 * 等待时间
                 *
                 * 单位：秒
                 */
                waitingTime: number;
                /**
                 * 任务预计完成时间
                 *
                 * 单位：秒
                 */
                taskFinishTime: number;
                /**
                 * 任务创建时间
                 *
                 * 时间戳，单位：毫秒
                 */
                createTime: number;
                /**
                 * 股票市场
                 *
                 * US-美股
                 * HK-港股
                 */
                marketCode: string;
                /**
                 * 是否使用vip提交任务
                 */
                useVip: boolean;
            }>;
        };
    };
};

export type PostApiOptionAnalysisGetHistoryTasksResponse = PostApiOptionAnalysisGetHistoryTasksResponses[keyof PostApiOptionAnalysisGetHistoryTasksResponses];
