// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PostApiOptionAnalysisAnalyzeTaskRealTimeData, PostApiOptionAnalysisAnalyzeTaskRealTimeResponses, PostApiOptionAnalysisCalcRealTimeTaskPriceData, PostApiOptionAnalysisCalcRealTimeTaskPriceResponses, PostApiOptionAnalysisGetHistoryTasksData, PostApiOptionAnalysisGetHistoryTasksResponses, PostApiOptionAnalysisGetTaskResultData, PostApiOptionAnalysisGetTaskResultResponses, PostApiOptionAnalysisThirdPartySubmitTaskData, PostApiOptionAnalysisThirdPartySubmitTaskResponses, PostApiOptionRechargeGetRechargeInfoData, PostApiOptionRechargeGetRechargeInfoResponses, PostApiOptionRechargeThirdPartyOpenVipData, PostApiOptionRechargeThirdPartyOpenVipResponses, PostApiOptionUserThirdPartyLoginData, PostApiOptionUserThirdPartyLoginResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 2.3 三方登录接口
 *
 * 用于同步三方用户信息
 * 调用时机：用户在三方平台登录成功后
 * 如果openId不存在，会新注册一个用户，如果存在则更新用户信息。
 */
export const postApiOptionUserThirdPartyLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionUserThirdPartyLoginData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionUserThirdPartyLoginResponses, unknown, ThrowOnError>({
    url: '/api/option/user/thirdPartyLogin',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 3.1 获取充值商品信息
 *
 * 获取金币充值和会员充值商品价格等信息
 */
export const postApiOptionRechargeGetRechargeInfo = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionRechargeGetRechargeInfoData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionRechargeGetRechargeInfoResponses, unknown, ThrowOnError>({
    url: '/api/option/recharge/getRechargeInfo',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 3.2 三方开通会员接口
 *
 * 使用场景：合作方用户扣费成功后，调用该接口给用户增加会员权益
 */
export const postApiOptionRechargeThirdPartyOpenVip = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionRechargeThirdPartyOpenVipData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionRechargeThirdPartyOpenVipResponses, unknown, ThrowOnError>({
    url: '/api/option/recharge/thirdPartyOpenVip',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 4.2 计算期权实时任务价格
 *
 * 点击提交按钮时，先调用该接口获取任务价格，用户确认后，再调用实时期权分析接口
 */
export const postApiOptionAnalysisCalcRealTimeTaskPrice = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionAnalysisCalcRealTimeTaskPriceData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionAnalysisCalcRealTimeTaskPriceResponses, unknown, ThrowOnError>({
    url: '/api/option/analysis/calcRealTimeTaskPrice',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 4.3 实时分析期权接口
 */
export const postApiOptionAnalysisAnalyzeTaskRealTime = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionAnalysisAnalyzeTaskRealTimeData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionAnalysisAnalyzeTaskRealTimeResponses, unknown, ThrowOnError>({
    url: '/api/option/analysis/analyzeTaskRealTime',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 4.4 三方期权分析任务提交接口
 */
export const postApiOptionAnalysisThirdPartySubmitTask = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionAnalysisThirdPartySubmitTaskData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionAnalysisThirdPartySubmitTaskResponses, unknown, ThrowOnError>({
    url: '/api/option/analysis/thirdPartySubmitTask',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 5.1 查询期权分析结果
 *
 * 用于查询历史任务的期权分析结果。先调用5.2历史任务查询接口，获取任务id，再通过该接口查询指定任务的分析结果
 */
export const postApiOptionAnalysisGetTaskResult = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionAnalysisGetTaskResultData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionAnalysisGetTaskResultResponses, unknown, ThrowOnError>({
    url: '/api/option/analysis/getTaskResult',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 5.2  历史任务查询接口
 *
 * 查询用户提交的历史任务列表
 */
export const postApiOptionAnalysisGetHistoryTasks = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionAnalysisGetHistoryTasksData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionAnalysisGetHistoryTasksResponses, unknown, ThrowOnError>({
    url: '/api/option/analysis/getHistoryTasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
