// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PostApiOptionGameFetchUsOptionChainData, PostApiOptionGameFetchUsOptionChainResponses, PostApiOptionGameFetchUsStockKLineData, PostApiOptionGameFetchUsStockKLineResponses, PostApiOptionGameListStockBuyCallPercentAdvData, PostApiOptionGameListStockBuyCallPercentAdvResponses, PostApiOptionGameListStockBuyPutPercentAdvData, PostApiOptionGameListStockBuyPutPercentAdvResponses, PostApiOptionGameQueryRealTimePriceData, PostApiOptionGameQueryRealTimePriceResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 6.1 期权实时价格查询
 */
export const postApiOptionGameQueryRealTimePrice = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionGameQueryRealTimePriceData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionGameQueryRealTimePriceResponses, unknown, ThrowOnError>({
    url: '/api/option/game/queryRealTimePrice',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 6.2 查询股票k线图
 */
export const postApiOptionGameFetchUsStockKLine = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionGameFetchUsStockKLineData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionGameFetchUsStockKLineResponses, unknown, ThrowOnError>({
    url: '/api/option/game/fetchUSStockKLine',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 6.3 查询期权链
 */
export const postApiOptionGameFetchUsOptionChain = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionGameFetchUsOptionChainData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionGameFetchUsOptionChainResponses, unknown, ThrowOnError>({
    url: '/api/option/game/fetchUSOptionChain',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 6.4 查询buyCall组合方案
 */
export const postApiOptionGameListStockBuyCallPercentAdv = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionGameListStockBuyCallPercentAdvData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionGameListStockBuyCallPercentAdvResponses, unknown, ThrowOnError>({
    url: '/api/option/game/listStockBuyCallPercentAdv',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 6.5 查询BuyPut组合方案
 */
export const postApiOptionGameListStockBuyPutPercentAdv = <ThrowOnError extends boolean = false>(options: Options<PostApiOptionGameListStockBuyPutPercentAdvData, ThrowOnError>) => (options.client ?? client).post<PostApiOptionGameListStockBuyPutPercentAdvResponses, unknown, ThrowOnError>({
    url: '/api/option/game/listStockBuyPutPercentAdv',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
